version: "3.9"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8001:8001"
    command: /start
  # elasticsearch:
  #   image: 'docker.elastic.co/elasticsearch/elasticsearch:8.5.3'
  #   container_name: elasticsearch
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - ES_JAVA_OPTS=-Xmx4g -Xms4g
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - '9200:9200'
