from django.urls import path, include
from gis.views import (
    ZonesList,
    NomenclatureList,
    ZonesTopoList,
    ZonesCosmoList,
    ZonesMapList,
    NomenclaturesTopoList,
    NomenclaturesCosmoList,
    NomenclaturesMapList,
    RanksList,
    RanksTopoList,
    RanksCosmoList,
    RanksMapList,
    ColumnsList,
    ColumnsTopoList,
    ColumnsCosmoList,
    ColumnsMapList,
)

urlpatterns = [
    path("zones/", ZonesList.as_view()),
    path("zones/<int:id>/topo/", ZonesTopoList.as_view()),
    path("zones/<int:id>/cosmo/", ZonesCosmoList.as_view()),
    path("zones/<int:id>/map/", ZonesMapList.as_view()),
    path("rank/", RanksList.as_view()),
    path("rank/<int:id>/topo/", RanksTopoList.as_view()),
    path("rank/<int:id>/cosmo/", RanksCosmoList.as_view()),
    path("rank/<int:id>/map/", RanksMapList.as_view()),
    path("column/", ColumnsList.as_view()),
    path("column/<int:id>/topo/", ColumnsTopoList.as_view()),
    path("column/<int:id>/cosmo/", ColumnsCosmoList.as_view()),
    path("column/<int:id>/map/", ColumnsMapList.as_view()),
    path("nomenclature/", NomenclatureList.as_view()),
    path("nomenclature/<int:id>/topo/", NomenclaturesTopoList.as_view()),
    path("nomenclature/<int:id>/cosmo/", NomenclaturesCosmoList.as_view()),
    path("nomenclature/<int:id>/map/", NomenclaturesMapList.as_view()),
]
