# Generated by Django 3.2 on 2023-09-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Nomenclatures title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Zones title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneTopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='zones-topo', verbose_name='Zone Topo')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topo', to='gis.zones', verbose_name='Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='zones-map', verbose_name='Zone map')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='gis.zones', verbose_name='Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneCosmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='zones-cosmo', verbose_name='Zone cosmo')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmo', to='gis.zones', verbose_name='Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NomenclatureTopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Nomenclatures Topo title')),
                ('image', models.ImageField(upload_to='nomenclatures-topo', verbose_name='Nomenclature Topo')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topo', to='gis.nomenclatures', verbose_name='Nomenclature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NomenclatureMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Nomenclatures Map title')),
                ('image', models.ImageField(upload_to='nomenclatures-map', verbose_name='Nomenclature map')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='gis.nomenclatures', verbose_name='Nomenclature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NomenclatureCosmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Nomenclatures Cosmo title')),
                ('image', models.ImageField(upload_to='nomenclatures-cosmo', verbose_name='Nomenclature cosmo')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmo', to='gis.nomenclatures', verbose_name='Nomenclature')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
